version: '3'

volumes:
  esdata1: {}
  aptdata: {}

services:
  crawling:
    build:
      context: .
      dockerfile: ./docker/crawling/Dockerfile
    container_name: crawling
    restart: always
    environment:
      - TZ=Asia/Seoul
      - PYTHONUNBUFFERED=1
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    #command: bash -c "python /code/elasticsearch_code/mapping.py"
    volumes:
      - ./:/code/
      - aptdata:/tmp
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    tty: true


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - LANG=ko_KR.UTF-8
      - LANGUAGE=ko_KR.UTF-8
      - TZ=Asia/Seoul
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - "9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
